"""initial canonical schema

The baseline: every table that existed before migrations were introduced (connections and
sync bookkeeping, plus the canonical health tables). Autogenerated from `Base.metadata`,
so an empty database upgraded to this revision matches what `init_db()` would have created
— `tests/test_migrations.py` asserts exactly that.

Revision ID: 0001
Revises:
Create Date: 2026-08-04
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "0001"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    op.create_table(
        "air_quality_reading",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("device_id", sa.String(), nullable=True),
        sa.Column("device_name", sa.String(), nullable=True),
        sa.Column("temp_c", sa.Float(), nullable=True),
        sa.Column("humidity_pct", sa.Float(), nullable=True),
        sa.Column("tvoc_ppb", sa.Float(), nullable=True),
        sa.Column("eco2_ppm", sa.Float(), nullable=True),
        sa.Column("pm1", sa.Float(), nullable=True),
        sa.Column("pm2_5", sa.Float(), nullable=True),
        sa.Column("pm10", sa.Float(), nullable=True),
        sa.Column("battery_pct", sa.Float(), nullable=True),
        sa.Column("source", sa.String(), nullable=False),
        sa.Column("source_external_id", sa.String(), nullable=False),
        sa.Column("recorded_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("score_state", sa.String(), nullable=True),
        sa.Column("ingested_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("raw", sa.JSON(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("source", "source_external_id", name="uq_air_quality_source_id"),
    )
    with op.batch_alter_table("air_quality_reading", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_air_quality_reading_device_id"), ["device_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_air_quality_reading_recorded_at"), ["recorded_at"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_air_quality_reading_source"), ["source"], unique=False)
        batch_op.create_index(
            batch_op.f("ix_air_quality_reading_source_external_id"),
            ["source_external_id"],
            unique=False,
        )

    op.create_table(
        "body_measurement",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("height_meter", sa.Float(), nullable=True),
        sa.Column("weight_kilogram", sa.Float(), nullable=True),
        sa.Column("max_heart_rate", sa.Integer(), nullable=True),
        sa.Column("source", sa.String(), nullable=False),
        sa.Column("source_external_id", sa.String(), nullable=False),
        sa.Column("recorded_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("score_state", sa.String(), nullable=True),
        sa.Column("ingested_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("raw", sa.JSON(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("source", "source_external_id", name="uq_body_source_id"),
    )
    with op.batch_alter_table("body_measurement", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_body_measurement_recorded_at"), ["recorded_at"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_body_measurement_source"), ["source"], unique=False)
        batch_op.create_index(
            batch_op.f("ix_body_measurement_source_external_id"),
            ["source_external_id"],
            unique=False,
        )

    op.create_table(
        "cycle_day",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("start", sa.DateTime(timezone=True), nullable=True),
        sa.Column("end", sa.DateTime(timezone=True), nullable=True),
        sa.Column("timezone_offset", sa.String(), nullable=True),
        sa.Column("strain", sa.Float(), nullable=True),
        sa.Column("kilojoule", sa.Float(), nullable=True),
        sa.Column("avg_hr_bpm", sa.Float(), nullable=True),
        sa.Column("max_hr_bpm", sa.Float(), nullable=True),
        sa.Column("source", sa.String(), nullable=False),
        sa.Column("source_external_id", sa.String(), nullable=False),
        sa.Column("recorded_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("score_state", sa.String(), nullable=True),
        sa.Column("ingested_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("raw", sa.JSON(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("source", "source_external_id", name="uq_cycle_source_id"),
    )
    with op.batch_alter_table("cycle_day", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_cycle_day_recorded_at"), ["recorded_at"], unique=False)
        batch_op.create_index(batch_op.f("ix_cycle_day_source"), ["source"], unique=False)
        batch_op.create_index(
            batch_op.f("ix_cycle_day_source_external_id"), ["source_external_id"], unique=False
        )

    op.create_table(
        "mill_connection",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("mill_user_id", sa.String(), nullable=True),
        sa.Column("access_token", sa.String(), nullable=False),
        sa.Column("refresh_token", sa.String(), nullable=True),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("mill_user_id"),
    )
    op.create_table(
        "profile",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("email", sa.String(), nullable=True),
        sa.Column("first_name", sa.String(), nullable=True),
        sa.Column("last_name", sa.String(), nullable=True),
        sa.Column("source", sa.String(), nullable=False),
        sa.Column("source_external_id", sa.String(), nullable=False),
        sa.Column("recorded_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("score_state", sa.String(), nullable=True),
        sa.Column("ingested_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("raw", sa.JSON(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("source", "source_external_id", name="uq_profile_source_id"),
    )
    with op.batch_alter_table("profile", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_profile_recorded_at"), ["recorded_at"], unique=False)
        batch_op.create_index(batch_op.f("ix_profile_source"), ["source"], unique=False)
        batch_op.create_index(
            batch_op.f("ix_profile_source_external_id"), ["source_external_id"], unique=False
        )

    op.create_table(
        "recovery_daily",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("cycle_id", sa.String(), nullable=True),
        sa.Column("sleep_id", sa.String(), nullable=True),
        sa.Column("recovery_score", sa.Float(), nullable=True),
        sa.Column("resting_hr_bpm", sa.Float(), nullable=True),
        sa.Column("hrv_rmssd_ms", sa.Float(), nullable=True),
        sa.Column("spo2_pct", sa.Float(), nullable=True),
        sa.Column("skin_temp_c", sa.Float(), nullable=True),
        sa.Column("user_calibrating", sa.Boolean(), nullable=True),
        sa.Column("source", sa.String(), nullable=False),
        sa.Column("source_external_id", sa.String(), nullable=False),
        sa.Column("recorded_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("score_state", sa.String(), nullable=True),
        sa.Column("ingested_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("raw", sa.JSON(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("source", "source_external_id", name="uq_recovery_source_id"),
    )
    with op.batch_alter_table("recovery_daily", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_recovery_daily_recorded_at"), ["recorded_at"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_recovery_daily_source"), ["source"], unique=False)
        batch_op.create_index(
            batch_op.f("ix_recovery_daily_source_external_id"), ["source_external_id"], unique=False
        )

    op.create_table(
        "sleep_session",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("start", sa.DateTime(timezone=True), nullable=True),
        sa.Column("end", sa.DateTime(timezone=True), nullable=True),
        sa.Column("timezone_offset", sa.String(), nullable=True),
        sa.Column("nap", sa.Boolean(), nullable=True),
        sa.Column("sleep_performance_pct", sa.Float(), nullable=True),
        sa.Column("sleep_consistency_pct", sa.Float(), nullable=True),
        sa.Column("sleep_efficiency_pct", sa.Float(), nullable=True),
        sa.Column("respiratory_rate", sa.Float(), nullable=True),
        sa.Column("total_in_bed_ms", sa.Integer(), nullable=True),
        sa.Column("total_awake_ms", sa.Integer(), nullable=True),
        sa.Column("total_light_ms", sa.Integer(), nullable=True),
        sa.Column("total_slow_wave_ms", sa.Integer(), nullable=True),
        sa.Column("total_rem_ms", sa.Integer(), nullable=True),
        sa.Column("total_no_data_ms", sa.Integer(), nullable=True),
        sa.Column("sleep_cycle_count", sa.Integer(), nullable=True),
        sa.Column("disturbance_count", sa.Integer(), nullable=True),
        sa.Column("source", sa.String(), nullable=False),
        sa.Column("source_external_id", sa.String(), nullable=False),
        sa.Column("recorded_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("score_state", sa.String(), nullable=True),
        sa.Column("ingested_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("raw", sa.JSON(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("source", "source_external_id", name="uq_sleep_source_id"),
    )
    with op.batch_alter_table("sleep_session", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_sleep_session_recorded_at"), ["recorded_at"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_sleep_session_source"), ["source"], unique=False)
        batch_op.create_index(
            batch_op.f("ix_sleep_session_source_external_id"), ["source_external_id"], unique=False
        )

    op.create_table(
        "sync_cursor",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("source", sa.String(), nullable=False),
        sa.Column("resource", sa.String(), nullable=False),
        sa.Column("last_synced_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("source", "resource", name="uq_cursor_source_resource"),
    )
    op.create_table(
        "vitals_timeseries",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("source", sa.String(), nullable=False),
        sa.Column("source_external_id", sa.String(), nullable=True),
        sa.Column("metric", sa.String(), nullable=False),
        sa.Column("ts", sa.DateTime(timezone=True), nullable=False),
        sa.Column("value", sa.Float(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("vitals_timeseries", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_vitals_timeseries_metric"), ["metric"], unique=False)
        batch_op.create_index(batch_op.f("ix_vitals_timeseries_source"), ["source"], unique=False)
        batch_op.create_index(
            batch_op.f("ix_vitals_timeseries_source_external_id"),
            ["source_external_id"],
            unique=False,
        )
        batch_op.create_index(batch_op.f("ix_vitals_timeseries_ts"), ["ts"], unique=False)

    op.create_table(
        "whoop_connection",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("whoop_user_id", sa.String(), nullable=True),
        sa.Column("access_token", sa.String(), nullable=False),
        sa.Column("refresh_token", sa.String(), nullable=True),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("scope", sa.String(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("whoop_user_id"),
    )
    op.create_table(
        "workout",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("start", sa.DateTime(timezone=True), nullable=True),
        sa.Column("end", sa.DateTime(timezone=True), nullable=True),
        sa.Column("timezone_offset", sa.String(), nullable=True),
        sa.Column("sport_id", sa.Integer(), nullable=True),
        sa.Column("sport_name", sa.String(), nullable=True),
        sa.Column("strain", sa.Float(), nullable=True),
        sa.Column("avg_hr_bpm", sa.Float(), nullable=True),
        sa.Column("max_hr_bpm", sa.Float(), nullable=True),
        sa.Column("kilojoule", sa.Float(), nullable=True),
        sa.Column("distance_meter", sa.Float(), nullable=True),
        sa.Column("altitude_gain_meter", sa.Float(), nullable=True),
        sa.Column("altitude_change_meter", sa.Float(), nullable=True),
        sa.Column("zone_durations", sa.JSON(), nullable=True),
        sa.Column("source", sa.String(), nullable=False),
        sa.Column("source_external_id", sa.String(), nullable=False),
        sa.Column("recorded_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("score_state", sa.String(), nullable=True),
        sa.Column("ingested_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("raw", sa.JSON(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("source", "source_external_id", name="uq_workout_source_id"),
    )
    with op.batch_alter_table("workout", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_workout_recorded_at"), ["recorded_at"], unique=False)
        batch_op.create_index(batch_op.f("ix_workout_source"), ["source"], unique=False)
        batch_op.create_index(
            batch_op.f("ix_workout_source_external_id"), ["source_external_id"], unique=False
        )

    op.create_table(
        "sleep_stage",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("sleep_session_id", sa.Integer(), nullable=False),
        sa.Column("stage_kind", sa.String(), nullable=False),
        sa.Column("duration_ms", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(["sleep_session_id"], ["sleep_session.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("sleep_stage", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_sleep_stage_sleep_session_id"), ["sleep_session_id"], unique=False
        )


def downgrade() -> None:
    with op.batch_alter_table("sleep_stage", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_sleep_stage_sleep_session_id"))

    op.drop_table("sleep_stage")
    with op.batch_alter_table("workout", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_workout_source_external_id"))
        batch_op.drop_index(batch_op.f("ix_workout_source"))
        batch_op.drop_index(batch_op.f("ix_workout_recorded_at"))

    op.drop_table("workout")
    op.drop_table("whoop_connection")
    with op.batch_alter_table("vitals_timeseries", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_vitals_timeseries_ts"))
        batch_op.drop_index(batch_op.f("ix_vitals_timeseries_source_external_id"))
        batch_op.drop_index(batch_op.f("ix_vitals_timeseries_source"))
        batch_op.drop_index(batch_op.f("ix_vitals_timeseries_metric"))

    op.drop_table("vitals_timeseries")
    op.drop_table("sync_cursor")
    with op.batch_alter_table("sleep_session", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_sleep_session_source_external_id"))
        batch_op.drop_index(batch_op.f("ix_sleep_session_source"))
        batch_op.drop_index(batch_op.f("ix_sleep_session_recorded_at"))

    op.drop_table("sleep_session")
    with op.batch_alter_table("recovery_daily", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_recovery_daily_source_external_id"))
        batch_op.drop_index(batch_op.f("ix_recovery_daily_source"))
        batch_op.drop_index(batch_op.f("ix_recovery_daily_recorded_at"))

    op.drop_table("recovery_daily")
    with op.batch_alter_table("profile", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_profile_source_external_id"))
        batch_op.drop_index(batch_op.f("ix_profile_source"))
        batch_op.drop_index(batch_op.f("ix_profile_recorded_at"))

    op.drop_table("profile")
    op.drop_table("mill_connection")
    with op.batch_alter_table("cycle_day", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_cycle_day_source_external_id"))
        batch_op.drop_index(batch_op.f("ix_cycle_day_source"))
        batch_op.drop_index(batch_op.f("ix_cycle_day_recorded_at"))

    op.drop_table("cycle_day")
    with op.batch_alter_table("body_measurement", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_body_measurement_source_external_id"))
        batch_op.drop_index(batch_op.f("ix_body_measurement_source"))
        batch_op.drop_index(batch_op.f("ix_body_measurement_recorded_at"))

    op.drop_table("body_measurement")
    with op.batch_alter_table("air_quality_reading", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_air_quality_reading_source_external_id"))
        batch_op.drop_index(batch_op.f("ix_air_quality_reading_source"))
        batch_op.drop_index(batch_op.f("ix_air_quality_reading_recorded_at"))
        batch_op.drop_index(batch_op.f("ix_air_quality_reading_device_id"))

    op.drop_table("air_quality_reading")
