"""derived layer tables

Adds the derived layer (V1 M2): `daily_summary` (one row per local date), `baseline`
(trailing mean/SD per metric and window) and `insight_card` (findings worth surfacing).

Also adds `sleep_session.sleep_debt_ms` — the one *existing* table this revision touches.
The daily summary carries sleep debt, and the canonical model had nowhere to put WHOOP's
`sleep_needed.need_from_sleep_debt_milli`; reading it out of `raw` downstream would have
leaked a source payload shape into the derived layer (global invariant #3).

Revision ID: 0002
Revises: 0001
Create Date: 2026-08-04
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "0002"
down_revision: str | None = "0001"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "baseline",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("metric", sa.String(), nullable=False),
        sa.Column("window", sa.Integer(), nullable=False),
        sa.Column("mean", sa.Float(), nullable=True),
        sa.Column("sd", sa.Float(), nullable=True),
        sa.Column("n", sa.Integer(), nullable=False),
        sa.Column("computed_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("metric", "window", name="uq_baseline_metric_window"),
    )
    with op.batch_alter_table("baseline", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_baseline_metric"), ["metric"], unique=False)

    op.create_table(
        "daily_summary",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("date", sa.Date(), nullable=False),
        sa.Column("recovery_score", sa.Float(), nullable=True),
        sa.Column("hrv_rmssd_ms", sa.Float(), nullable=True),
        sa.Column("resting_hr_bpm", sa.Float(), nullable=True),
        sa.Column("spo2_pct", sa.Float(), nullable=True),
        sa.Column("skin_temp_c", sa.Float(), nullable=True),
        sa.Column("sleep_performance_pct", sa.Float(), nullable=True),
        sa.Column("sleep_efficiency_pct", sa.Float(), nullable=True),
        sa.Column("sleep_duration_ms", sa.Integer(), nullable=True),
        sa.Column("sleep_debt_ms", sa.Integer(), nullable=True),
        sa.Column("rem_ms", sa.Integer(), nullable=True),
        sa.Column("slow_wave_ms", sa.Integer(), nullable=True),
        sa.Column("respiratory_rate", sa.Float(), nullable=True),
        sa.Column("disturbance_count", sa.Integer(), nullable=True),
        sa.Column("day_strain", sa.Float(), nullable=True),
        sa.Column("workout_count", sa.Integer(), nullable=True),
        sa.Column("workout_strain_sum", sa.Float(), nullable=True),
        sa.Column("kilojoule", sa.Float(), nullable=True),
        sa.Column("night_temp_c_avg", sa.Float(), nullable=True),
        sa.Column("night_eco2_ppm_avg", sa.Float(), nullable=True),
        sa.Column("night_eco2_ppm_max", sa.Float(), nullable=True),
        sa.Column("night_tvoc_ppb_avg", sa.Float(), nullable=True),
        sa.Column("night_humidity_pct_avg", sa.Float(), nullable=True),
        sa.Column("weather_temp_min_c", sa.Float(), nullable=True),
        sa.Column("weather_temp_max_c", sa.Float(), nullable=True),
        sa.Column("daylight_seconds", sa.Integer(), nullable=True),
        sa.Column("sunrise", sa.DateTime(timezone=True), nullable=True),
        sa.Column("sunset", sa.DateTime(timezone=True), nullable=True),
        sa.Column("checkin_mood", sa.Integer(), nullable=True),
        sa.Column("checkin_energy", sa.Integer(), nullable=True),
        sa.Column("checkin_stress", sa.Integer(), nullable=True),
        sa.Column("checkin_soreness", sa.Integer(), nullable=True),
        sa.Column("alcohol_units", sa.Float(), nullable=True),
        sa.Column("caffeine_after_14", sa.Boolean(), nullable=True),
        sa.Column("last_caffeine_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("readiness_score", sa.Float(), nullable=True),
        sa.Column("readiness_components", sa.JSON(), nullable=True),
        sa.Column("flags", sa.JSON(), nullable=True),
        sa.Column("source", sa.String(), nullable=False),
        sa.Column("source_external_id", sa.String(), nullable=False),
        sa.Column("recorded_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("score_state", sa.String(), nullable=True),
        sa.Column("ingested_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("raw", sa.JSON(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("source", "source_external_id", name="uq_daily_summary_source_id"),
    )
    with op.batch_alter_table("daily_summary", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_daily_summary_date"), ["date"], unique=True)
        batch_op.create_index(
            batch_op.f("ix_daily_summary_recorded_at"), ["recorded_at"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_daily_summary_source"), ["source"], unique=False)
        batch_op.create_index(
            batch_op.f("ix_daily_summary_source_external_id"), ["source_external_id"], unique=False
        )

    op.create_table(
        "insight_card",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("kind", sa.String(), nullable=False),
        sa.Column("title", sa.String(), nullable=False),
        sa.Column("body", sa.String(), nullable=False),
        sa.Column("metric_x", sa.String(), nullable=True),
        sa.Column("metric_y", sa.String(), nullable=True),
        sa.Column("effect_size", sa.Float(), nullable=True),
        sa.Column("n", sa.Integer(), nullable=True),
        sa.Column("p_value", sa.Float(), nullable=True),
        sa.Column("lag_days", sa.Integer(), nullable=True),
        sa.Column("first_seen", sa.DateTime(timezone=True), nullable=False),
        sa.Column("last_confirmed", sa.DateTime(timezone=True), nullable=False),
        sa.Column("status", sa.String(), nullable=False),
        sa.Column("source", sa.String(), nullable=False),
        sa.Column("source_external_id", sa.String(), nullable=False),
        sa.Column("recorded_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("score_state", sa.String(), nullable=True),
        sa.Column("ingested_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("raw", sa.JSON(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("source", "source_external_id", name="uq_insight_card_source_id"),
    )
    with op.batch_alter_table("insight_card", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_insight_card_kind"), ["kind"], unique=False)
        batch_op.create_index(
            batch_op.f("ix_insight_card_recorded_at"), ["recorded_at"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_insight_card_source"), ["source"], unique=False)
        batch_op.create_index(
            batch_op.f("ix_insight_card_source_external_id"), ["source_external_id"], unique=False
        )

    with op.batch_alter_table("sleep_session", schema=None) as batch_op:
        batch_op.add_column(sa.Column("sleep_debt_ms", sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("sleep_session", schema=None) as batch_op:
        batch_op.drop_column("sleep_debt_ms")

    with op.batch_alter_table("insight_card", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_insight_card_source_external_id"))
        batch_op.drop_index(batch_op.f("ix_insight_card_source"))
        batch_op.drop_index(batch_op.f("ix_insight_card_recorded_at"))
        batch_op.drop_index(batch_op.f("ix_insight_card_kind"))

    op.drop_table("insight_card")
    with op.batch_alter_table("daily_summary", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_daily_summary_source_external_id"))
        batch_op.drop_index(batch_op.f("ix_daily_summary_source"))
        batch_op.drop_index(batch_op.f("ix_daily_summary_recorded_at"))
        batch_op.drop_index(batch_op.f("ix_daily_summary_date"))

    op.drop_table("daily_summary")
    with op.batch_alter_table("baseline", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_baseline_metric"))

    op.drop_table("baseline")
    # ### end Alembic commands ###
